name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          release-type: python
          token: ${{ secrets.RELEASE_PLEASE_PR_CI_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ steps.release.outputs.release_created }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          enable-cache: true

      - name: Install Python 3.11
        if: ${{ steps.release.outputs.release_created }}
        run: uv python install 3.11

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run:  make install-ci

      - name: Build a binary wheel and a source tarball
        if: ${{ steps.release.outputs.release_created }}
        run:  make build

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          user:     __token__
          password: ${{ secrets.PYPI_TOKEN }}
