name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-n-publish:
    name:    Build and publish to PyPI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run:  make install-ci
      - name: Build a binary wheel and a source tarball
        run:  make build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user:     __token__
          password: ${{ secrets.PYPI_TOKEN }}

  push_to_registry:
    name:    Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username:     ${{ secrets.DOCKER_USERNAME }}
          password:     ${{ secrets.DOCKER_TOKEN }}
          repository:   snakemake/snakefmt
          tags:         latest
          tag_with_ref: true
